version: '3'
services:
  frontend:
    build:
      context: ./ocr-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./ocr-backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/ocrdb
    volumes:
      - ./ocr-backend/uploads:/usr/src/app/uploads
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: